# ----------- CONFIGURABLE START -----------
title:            "Tate & Snow"
description:      "Lovely Home"
url:              https://tate-young.github.io # 域名
signoff:          "Tate" # Your name
facebook_appid:   #Tate
google_analytics: UA-101222464-1
share:            true
# 分页
paginate: 15
paginate_path: "blog:num"
plugins: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         前端
    url:          /front
    external:     false
  - name:         框架
    url:          /tool
    external:     false
  - name:         后端
    url:          /back
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /README
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"

jekyll_admin:
  hidden_links:
    - pages
